Repository sanghoro/RancidTomatillos, pull requests merged in 2024-07, with the labels that each got.

#9 Feat/basic structure setup
  src/App.css
  src/App.js
  src/MockData/mock-data.js
  src/componentStyles/Footer.css
  src/componentStyles/Header.css
  src/componentStyles/Main.css
  src/componentStyles/MovieCard.css
  src/componentStyles/Nav.css
  src/components/Footer.js
  src/components/Header.js
  src/components/Main.js
  src/components/MovieCard.js
  src/components/Nav.js
  src/logo.svg
Labels: iteration 1, Design

#10 iteration 1 / Feat-Initial View Of Movie Cards + Basic Styling + Fetch
  package-lock.json
  package.json
  src/App.js
  src/componentStyles/Main.css
  src/componentStyles/MovieCard.css
  src/components/Main.js
  src/components/MovieCard.js
Labels: iteration 1, Design, iteration 3, Fetch/Post

#11 Feat/displaying individual movie
  package-lock.json
  package.json
  src/App.js
  src/componentStyles/MovieDetails.css
  src/components/Main.js
  src/components/MovieCard.js
  src/components/MovieDetails.js
Labels: Design, iteration 3, iteration 2, Fetch/Post

#12 Feat/movie details page
  src/App.css
  src/App.js
  src/componentStyles/Footer.css
  src/componentStyles/Header.css
  src/componentStyles/Main.css
  src/componentStyles/MovieDetails.css
  src/components/Header.js
  src/components/Main.js
  src/components/MovieDetails.js
  src/index.js
Labels: iteration 3, iteration 4, Fetch/Post

#17 Feat/Fixing Navbar & Search bar & Movie Details Page
  src/App.css
  src/componentStyles/Footer.css
  src/componentStyles/Header.css
  src/componentStyles/Main.css
  src/componentStyles/MovieCard.css
  src/componentStyles/MovieDetails.css
  src/componentStyles/Nav.css
  src/components/MovieCard.js
  src/components/MovieDetails.js
  src/components/Nav.js
  src/img/Logo1.png
Labels: bug, Design

#18 Feat/show trailers
  cypress/e2e/homepage.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/App.js
  src/componentStyles/Header.css
  src/componentStyles/MovieDetails.css
  src/components/Header.js
  src/components/MovieDetails.js
  src/components/Nav.js
Labels: Design, iteration 4

#19 Feat/cypress+footer design+minor adjustments
  cypress.config.js
  cypress/e2e/homepage.cy.js
  src/App.js
  src/componentStyles/Footer.css
  src/componentStyles/MovieCard.css
  src/components/Footer.js
  src/components/Main.js
  src/components/MovieCard.js
  src/img/github-Icon.png
  src/img/linkedin-icon.png
Labels: Design, iteration 4, Cypress Testing

#20 added styling on main poster
  src/App.js
  src/componentStyles/Header.css
  src/componentStyles/MovieCard.css
  src/components/Main.js
  src/components/MovieCard.js
  src/components/Nav.js
  src/img/full-tomato.png
  src/img/half-tomato.png
Labels: Design

#21 Added Cypress MockData
  cypress/e2e/homepage.cy.js
  cypress/fixtures/movies.json
Labels: Cypress Testing

#24 Add Search bar functionality and styling updates
  public/index.html
  src/App.css
  src/App.js
  src/componentStyles/MovieCard.css
  src/componentStyles/MovieDetails.css
  src/componentStyles/Nav.css
  src/components/Header.js
  src/components/Main.js
  src/components/MovieDetails.js
  src/components/Nav.js
  src/img/search.png
Labels: Design, iteration 5

#25 Feat/ Add more details to movieDetails
  src/App.js
  src/componentStyles/MovieDetails.css
  src/componentStyles/Nav.css
  src/components/Header.js
  src/components/Main.js
  src/components/MovieDetails.js
  src/components/Nav.js
Labels: bug, Design, iteration 5
